-- P0 Trading Funnel Shadow Trace schema
-- Shadow/read-only observability tables only. No Flyway dependency is required;
-- apply manually or through existing DB operations when needed.

CREATE TABLE IF NOT EXISTS trading_funnel_trace (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    trading_date DATE NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    stock_name VARCHAR(120),
    theme_tag VARCHAR(120),
    signal_id BIGINT,
    signal_source VARCHAR(80),
    signal_role VARCHAR(40),
    signal_strength DECIMAL(12,4),
    signal_change_pct DECIMAL(12,4),
    signal_near_limit BOOLEAN,
    signal_limit_risk VARCHAR(80),
    candidate_status VARCHAR(40),
    candidate_reason VARCHAR(500),
    candidate_id BIGINT,
    watchlist_status VARCHAR(40),
    watchlist_reason VARCHAR(500),
    watchlist_id BIGINT,
    ranking_status VARCHAR(40),
    ranking_rank INT,
    ranking_score DECIMAL(12,4),
    ranking_reason VARCHAR(500),
    ranking_snapshot_id BIGINT,
    setup_status VARCHAR(40),
    setup_reason VARCHAR(500),
    setup_decision_id BIGINT,
    risk_status VARCHAR(40),
    risk_reason VARCHAR(500),
    risk_decision_id BIGINT,
    portfolio_status VARCHAR(40),
    portfolio_reason VARCHAR(500),
    position_id BIGINT,
    buy_status VARCHAR(40),
    buy_reason VARCHAR(500),
    buy_trade_id BIGINT,
    buy_trade_ref VARCHAR(120),
    exit_status VARCHAR(40),
    exit_reason VARCHAR(500),
    exit_ref_id BIGINT,
    final_outcome_1d DECIMAL(12,4),
    final_outcome_5d DECIMAL(12,4),
    final_outcome_10d DECIMAL(12,4),
    max_drawdown_10d DECIMAL(12,4),
    blocked_stage VARCHAR(40),
    blocked_reason VARCHAR(500),
    trace_source VARCHAR(40) NOT NULL DEFAULT 'SHADOW',
    trace_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_trading_funnel_trace_date (trading_date),
    INDEX idx_trading_funnel_trace_symbol_date (symbol, trading_date),
    INDEX idx_trading_funnel_trace_theme_date (theme_tag, trading_date),
    INDEX idx_trading_funnel_trace_blocked (blocked_stage, trading_date),
    INDEX idx_trading_funnel_trace_status (trace_status, trading_date)
);

CREATE TABLE IF NOT EXISTS theme_admission_shadow_decision (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    trading_date DATE NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    stock_name VARCHAR(120),
    theme_tag VARCHAR(120) NOT NULL,
    signal_id BIGINT,
    signal_role VARCHAR(40),
    current_action VARCHAR(60),
    current_reason VARCHAR(500),
    shadow_action VARCHAR(40) NOT NULL,
    shadow_reason VARCHAR(500),
    would_write_candidate BOOLEAN,
    would_write_watchlist BOOLEAN,
    would_create_pullback_plan BOOLEAN,
    would_bypass_top_n BOOLEAN,
    blocked_by_current_stage VARCHAR(80),
    delta_stage VARCHAR(80),
    admission_score DECIMAL(12,4),
    theme_strength DECIMAL(12,4),
    signal_strength DECIMAL(12,4),
    rank_in_theme INT,
    near_limit BOOLEAN,
    limit_risk VARCHAR(80),
    source_trace_id BIGINT,
    evidence_json JSON,
    trace_source VARCHAR(40) NOT NULL DEFAULT 'SHADOW',
    trace_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_theme_admission_shadow_date_symbol_theme_signal (trading_date, symbol, theme_tag, signal_id),
    INDEX idx_theme_admission_shadow_date (trading_date),
    INDEX idx_theme_admission_shadow_symbol_date (symbol, trading_date),
    INDEX idx_theme_admission_shadow_theme_date (theme_tag, trading_date),
    INDEX idx_theme_admission_shadow_action (shadow_action, trading_date)
);

CREATE TABLE IF NOT EXISTS ranking_topn_shadow_result (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    trading_date DATE NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    snapshot_id BIGINT,
    symbol VARCHAR(20) NOT NULL,
    stock_name VARCHAR(120),
    theme_tag VARCHAR(120),
    bucket VARCHAR(40),
    current_selected BOOLEAN,
    would_select_top5 BOOLEAN,
    would_select_top10 BOOLEAN,
    would_select_top20 BOOLEAN,
    ranking_rank INT,
    ranking_score DECIMAL(12,4),
    ranking_status VARCHAR(40),
    ranking_reason VARCHAR(500),
    candidate_id BIGINT,
    source_trace_id BIGINT,
    actual_return_1d DECIMAL(12,4),
    actual_return_5d DECIMAL(12,4),
    actual_return_10d DECIMAL(12,4),
    max_drawdown_10d DECIMAL(12,4),
    missed_by_top3 BOOLEAN,
    score_breakdown_json JSON,
    trace_source VARCHAR(40) NOT NULL DEFAULT 'SHADOW',
    trace_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ranking_topn_shadow_date_run_symbol (trading_date, run_id, symbol),
    INDEX idx_ranking_topn_shadow_date_rank (trading_date, ranking_rank),
    INDEX idx_ranking_topn_shadow_symbol_date (symbol, trading_date),
    INDEX idx_ranking_topn_shadow_theme_date (theme_tag, trading_date),
    INDEX idx_ranking_topn_shadow_run (run_id)
);
