-- P1.2 Trade Attribution: per-trade setup/regime/timing/theme metrics for weekly learning
CREATE TABLE IF NOT EXISTS trade_attribution (
    id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    position_id          BIGINT       NOT NULL UNIQUE,
    symbol               VARCHAR(20)  NOT NULL,
    entry_date           DATE,
    exit_date            DATE,
    setup_type           VARCHAR(40),
    regime_type          VARCHAR(30),
    theme_stage          VARCHAR(30),
    timing_mode          VARCHAR(30),
    ideal_entry_price    DECIMAL(12,4),
    actual_entry_price   DECIMAL(12,4),
    delay_pct            DECIMAL(8,4)  COMMENT '(actual-ideal)/ideal*100',
    mfe_pct              DECIMAL(8,4)  COMMENT 'max favorable excursion %',
    mae_pct              DECIMAL(8,4)  COMMENT 'max adverse excursion %',
    pnl_pct              DECIMAL(8,4),
    timing_quality       VARCHAR(10)   COMMENT 'GOOD|FAIR|POOR|UNKNOWN',
    exit_quality         VARCHAR(10)   COMMENT 'GOOD|FAIR|POOR|UNKNOWN',
    sizing_quality       VARCHAR(10)   COMMENT 'GOOD|FAIR|POOR|UNKNOWN',
    regime_decision_id   BIGINT,
    setup_decision_id    BIGINT,
    timing_decision_id   BIGINT,
    theme_decision_id    BIGINT,
    execution_decision_id BIGINT,
    payload_json         JSON,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_attr_position (position_id),
    INDEX idx_attr_symbol   (symbol),
    INDEX idx_attr_setup    (setup_type),
    INDEX idx_attr_regime   (regime_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
