CREATE TABLE IF NOT EXISTS missed_rally_tracking (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trading_date DATE,
    stock_id VARCHAR(20),
    stock_name VARCHAR(80),
    original_decision VARCHAR(40),
    original_grade VARCHAR(40),
    original_score DECIMAL(12,4),
    primary_strategy VARCHAR(40),
    reject_reason VARCHAR(1000),
    gate_name VARCHAR(80),
    current_price_at_decision DECIMAL(12,4),
    next_day_high DECIMAL(12,4),
    next_day_close DECIMAL(12,4),
    t3_high DECIMAL(12,4),
    t3_close DECIMAL(12,4),
    t5_high DECIMAL(12,4),
    t5_close DECIMAL(12,4),
    t10_high DECIMAL(12,4),
    t10_close DECIMAL(12,4),
    max_return_pct DECIMAL(12,4),
    close_return_pct DECIMAL(12,4),
    mfe_pct DECIMAL(12,4),
    mae_pct DECIMAL(12,4),
    would_have_hit_stop BOOLEAN,
    would_have_hit_target BOOLEAN,
    missed_rally_flag BOOLEAN,
    missed_rally_reason VARCHAR(1000),
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE IF NOT EXISTS candidate_forward_tracking (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trading_date DATE,
    stock_id VARCHAR(20),
    stock_name VARCHAR(80),
    final_decision VARCHAR(40),
    final_score DECIMAL(12,4),
    grade VARCHAR(40),
    primary_strategy VARCHAR(40),
    gate_name VARCHAR(80),
    entry_price_at_decision DECIMAL(12,4),
    t1_close_return_pct DECIMAL(12,4),
    t3_close_return_pct DECIMAL(12,4),
    t5_close_return_pct DECIMAL(12,4),
    t10_close_return_pct DECIMAL(12,4),
    mfe_pct DECIMAL(12,4),
    mae_pct DECIMAL(12,4),
    hit_stop BOOLEAN,
    hit_target BOOLEAN,
    benchmark_return_pct DECIMAL(12,4),
    relative_return_pct DECIMAL(12,4),
    created_at DATETIME,
    updated_at DATETIME
);
