CREATE TABLE IF NOT EXISTS strategy_tuning_recommendation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    generated_date DATE NOT NULL,
    lookback_days INT NOT NULL,
    recommendation_type VARCHAR(50) NOT NULL,
    target_module VARCHAR(80) NOT NULL,
    target_parameter VARCHAR(120) NOT NULL,
    current_value VARCHAR(500),
    suggested_value VARCHAR(500),
    suggested_action VARCHAR(1000),
    reason VARCHAR(1500),
    evidence_json JSON,
    sample_size INT,
    win_rate DECIMAL(12,4),
    avg_return_pct DECIMAL(12,4),
    avg_mfe_pct DECIMAL(12,4),
    avg_mae_pct DECIMAL(12,4),
    missed_rally_rate DECIMAL(12,4),
    benchmark_relative_return_pct DECIMAL(12,4),
    confidence VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    approved_by VARCHAR(120),
    approved_at DATETIME,
    rejected_by VARCHAR(120),
    rejected_at DATETIME,
    applied_at DATETIME,
    rollback_value VARCHAR(500),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_str_status (status),
    INDEX idx_str_generated_date (generated_date),
    INDEX idx_str_target (target_module, target_parameter)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS strategy_tuning_history (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    recommendation_id BIGINT NOT NULL,
    applied_date DATETIME NOT NULL,
    target_module VARCHAR(80) NOT NULL,
    target_parameter VARCHAR(120) NOT NULL,
    old_value VARCHAR(500),
    new_value VARCHAR(500),
    applied_by VARCHAR(120),
    rollback_value VARCHAR(500),
    before_metrics_json JSON,
    after_metrics_json JSON,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_sth_recommendation (recommendation_id),
    CONSTRAINT fk_sth_recommendation FOREIGN KEY (recommendation_id)
        REFERENCES strategy_tuning_recommendation(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 現有 runtime config 使用 score_config；本 migration 只補 self-tuning 可調 key 的預設列。
INSERT IGNORE INTO score_config (config_key, config_value, value_type, description) VALUES
('scoring.enter_min_score', '6.5', 'DECIMAL', 'Self-tuning 可調：FinalDecision ENTER 最低分數'),
('scoring.watch_min_score', '5.0', 'DECIMAL', 'Self-tuning 可調：WATCH 最低分數'),
('breakout.min_score', '7.0', 'DECIMAL', 'Self-tuning 可調：Breakout 最低分數'),
('breakout.near_high_allowed', 'true', 'BOOLEAN', 'Self-tuning 可調：Breakout 是否允許接近日高'),
('breakout.enter_small_enabled', 'true', 'BOOLEAN', 'Self-tuning 可調：Breakout 是否允許 ENTER_SMALL'),
('pullback.min_score', '7.0', 'DECIMAL', 'Self-tuning 可調：Pullback 最低分數'),
('pullback.entry_zone_pct', '0.015', 'DECIMAL', 'Self-tuning 可調：Pullback entry zone'),
('pullback.support_distance_max', '0.03', 'DECIMAL', 'Self-tuning 可調：Pullback 支撐最大距離'),
('continuation.min_score', '7.0', 'DECIMAL', 'Self-tuning 可調：Continuation 最低分數'),
('continuation.rr_min', '1.5', 'DECIMAL', 'Self-tuning 可調：Continuation RR 下限'),
('continuation.enter_small_enabled', 'true', 'BOOLEAN', 'Self-tuning 可調：Continuation 是否允許 ENTER_SMALL'),
('gate.near_day_high_reject_threshold', '0.02', 'DECIMAL', 'Self-tuning 可調：接近日高拒絕門檻'),
('gate.chased_high_threshold', '0.05', 'DECIMAL', 'Self-tuning 可調：追高門檻'),
('risk.max_position_size_pct', '0.20', 'DECIMAL', 'Self-tuning 可調：單檔最大倉位'),
('risk.stop_loss_pct', '0.05', 'DECIMAL', 'Self-tuning 可調：預設停損');
