CREATE TABLE IF NOT EXISTS rr_shadow_validation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    paper_trade_id BIGINT NULL,
    trading_date DATE NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    strategy_type VARCHAR(30) NULL,
    entry_price DECIMAL(12,4) NULL,
    stop_loss_price DECIMAL(12,4) NULL,
    target1_price DECIMAL(12,4) NULL,
    target2_price DECIMAL(12,4) NULL,
    rr_ratio DECIMAL(12,4) NULL,
    shadow_status VARCHAR(20) NOT NULL,
    root_cause_bucket VARCHAR(60) NULL,
    t1_return_pct DECIMAL(12,4) NULL,
    t3_return_pct DECIMAL(12,4) NULL,
    t5_return_pct DECIMAL(12,4) NULL,
    t10_return_pct DECIMAL(12,4) NULL,
    avoided_loser_flag BOOLEAN NOT NULL DEFAULT FALSE,
    missed_winner_flag BOOLEAN NOT NULL DEFAULT FALSE,
    data_gap_reason VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_rr_shadow_validation_paper_trade (paper_trade_id),
    KEY idx_rr_shadow_validation_date (trading_date),
    KEY idx_rr_shadow_validation_status (shadow_status),
    KEY idx_rr_shadow_validation_bucket (root_cause_bucket)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
