-- Narrative Intelligence Layer foundation.
--
-- This migration creates production-facing narrative_* tables while keeping the
-- existing kol_* MVP path intact. These tables are additive only: no BUY signal,
-- no risk gate override, no FinalDecisionEngine override.

CREATE TABLE IF NOT EXISTS narrative_signal (
    id                         BIGINT AUTO_INCREMENT PRIMARY KEY,
    trading_date               DATE          NOT NULL,
    source_key                 VARCHAR(160)  NOT NULL,
    source_type                VARCHAR(40)   NOT NULL,
    source_name                VARCHAR(200)  NULL,
    episode_id                 VARCHAR(160)  NULL,
    episode_title              VARCHAR(300)  NULL,
    source_url                 VARCHAR(1000) NULL,
    published_at               TIMESTAMP     NULL,
    ingested_at                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content_hash               CHAR(64)      NOT NULL,
    raw_content                MEDIUMTEXT    NULL,
    raw_content_path           VARCHAR(1000) NULL,
    ai_summary                 TEXT          NULL,
    extraction_status          VARCHAR(40)   NOT NULL DEFAULT 'RAW',
    extraction_model           VARCHAR(120)  NULL,
    extraction_prompt_version  VARCHAR(80)   NULL,
    mentioned_themes_json      JSON          NULL,
    mentioned_stocks_json      JSON          NULL,
    source_language            VARCHAR(20)   NULL,
    market_regime              VARCHAR(40)   NULL,
    freshness_score            DECIMAL(6,3)  NULL,
    conviction_score           DECIMAL(6,3)  NULL,
    uncertainty_score          DECIMAL(6,3)  NULL,
    crowding_score             DECIMAL(6,3)  NULL,
    confidence                 DECIMAL(6,3)  NULL,
    status                     VARCHAR(40)   NOT NULL DEFAULT 'ACTIVE',
    payload_json               JSON          NULL,
    created_at                 TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_narrative_content_hash (content_hash),
    KEY idx_narrative_date_source (trading_date, source_key),
    KEY idx_narrative_published (published_at),
    KEY idx_narrative_status (trading_date, extraction_status, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS theme_signal (
    id                       BIGINT AUTO_INCREMENT PRIMARY KEY,
    narrative_signal_id       BIGINT       NOT NULL,
    trading_date              DATE         NOT NULL,
    theme_tag                 VARCHAR(120) NOT NULL,
    theme_alias               VARCHAR(200) NULL,
    normalized_theme_id       BIGINT       NULL,
    direction                 VARCHAR(40)  NOT NULL DEFAULT 'UNKNOWN',
    tone                      VARCHAR(40)  NOT NULL DEFAULT 'MIXED',
    narrative_direction       VARCHAR(40)  NULL,
    lifecycle_hint            VARCHAR(40)  NULL,
    conviction_score          DECIMAL(6,3) NULL,
    freshness_score           DECIMAL(6,3) NULL,
    novelty_score             DECIMAL(6,3) NULL,
    uncertainty_score         DECIMAL(6,3) NULL,
    crowding_score            DECIMAL(6,3) NULL,
    evidence_level            VARCHAR(40)  NULL,
    evidence_weight           DECIMAL(6,3) NULL,
    confidence                DECIMAL(6,3) NULL,
    reason_summary            VARCHAR(1200) NULL,
    risk_summary              VARCHAR(1200) NULL,
    payload_json              JSON         NULL,
    created_at                TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_theme_signal_date_theme (trading_date, theme_tag),
    KEY idx_theme_signal_theme_date (theme_tag, trading_date),
    KEY idx_theme_signal_direction (trading_date, direction),
    CONSTRAINT fk_theme_signal_narrative
        FOREIGN KEY (narrative_signal_id) REFERENCES narrative_signal(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS theme_lifecycle_snapshot (
    id                                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    trading_date                         DATE         NOT NULL,
    theme_tag                            VARCHAR(120) NOT NULL,
    lifecycle_stage                      VARCHAR(40)  NOT NULL,
    previous_stage                       VARCHAR(40)  NULL,
    mention_frequency_score              DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    source_density_score                 DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    media_spread_score                   DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    spread_velocity_score                DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    price_extension_score                DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    turnover_heat_score                  DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    retail_crowding_score                DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    institutional_participation_score    DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    lifecycle_confidence                 DECIMAL(6,3) NULL,
    recommended_effect                   VARCHAR(80)  NOT NULL DEFAULT 'CONTEXT_ONLY',
    weight_factor                        DECIMAL(6,3) NOT NULL DEFAULT 1.000,
    sizing_factor                        DECIMAL(6,3) NOT NULL DEFAULT 1.000,
    entry_aggressiveness                 VARCHAR(40)  NOT NULL DEFAULT 'NORMAL',
    stop_strategy                        VARCHAR(80)  NOT NULL DEFAULT 'NORMAL',
    risk_flags_json                      JSON         NULL,
    evidence_json                        JSON         NULL,
    payload_json                         JSON         NULL,
    generated_at                         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_theme_lifecycle_date_theme (trading_date, theme_tag),
    KEY idx_theme_lifecycle_stage (trading_date, lifecycle_stage),
    KEY idx_theme_lifecycle_theme_date (theme_tag, trading_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS narrative_theme_daily_snapshot (
    id                                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    trading_date                         DATE         NOT NULL,
    theme_tag                            VARCHAR(120) NOT NULL,
    attention_score                      DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    conviction_score                     DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    freshness_score                      DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    spread_velocity_score                DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    cross_source_confirmation_score      DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    rotation_score                       DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    crowding_score                       DECIMAL(6,3) NOT NULL DEFAULT 0.000,
    lifecycle_stage                      VARCHAR(40)  NULL,
    lifecycle_factor                     DECIMAL(6,3) NOT NULL DEFAULT 1.000,
    theme_strength_shadow                DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
    theme_boost_shadow                   DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
    theme_penalty_shadow                 DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
    source_count                         INT          NOT NULL DEFAULT 0,
    independent_source_count             INT          NOT NULL DEFAULT 0,
    evidence_count                       INT          NOT NULL DEFAULT 0,
    mentioned_stock_count                INT          NOT NULL DEFAULT 0,
    top_sources_json                     JSON         NULL,
    top_symbols_json                     JSON         NULL,
    evidence_json                        JSON         NULL,
    risk_flags_json                      JSON         NULL,
    aggregation_version                  VARCHAR(80)  NOT NULL,
    payload_json                         JSON         NULL,
    generated_at                         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_narrative_daily_date_theme (trading_date, theme_tag),
    KEY idx_narrative_daily_strength (trading_date, theme_strength_shadow),
    KEY idx_narrative_daily_crowding (trading_date, crowding_score),
    KEY idx_narrative_daily_lifecycle (trading_date, lifecycle_stage)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
