CREATE TABLE IF NOT EXISTS theme_leadership_snapshot (
    id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    trading_date          DATE          NOT NULL,
    source_phase          VARCHAR(32)   NOT NULL,
    symbol                VARCHAR(20)   NOT NULL,
    stock_name            VARCHAR(120)  NULL,
    theme_tag             VARCHAR(100)  NULL,
    theme_category        VARCHAR(80)   NULL,
    sub_theme             VARCHAR(100)  NULL,
    leader_rank           INT           NULL,
    hot_stock_rank        INT           NULL,
    super_strong_rank     INT           NULL,
    price_change_pct      DECIMAL(8,4)  NULL,
    turnover              DECIMAL(18,2) NULL,
    score                 DECIMAL(8,4)  NULL,
    close_near_high       BOOLEAN       NULL,
    tradable              BOOLEAN       NULL,
    tradable_reason       VARCHAR(500)  NULL,
    retention_reason      VARCHAR(500)  NULL,
    taxonomy_status       VARCHAR(50)   NULL,
    divergence_flags_json JSON          NULL,
    payload_json          JSON          NULL,
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_theme_leader_date_phase_symbol (trading_date, source_phase, symbol),
    KEY idx_theme_leader_date_theme (trading_date, theme_tag),
    KEY idx_theme_leader_date_rank (trading_date, leader_rank),
    KEY idx_theme_leader_phase (trading_date, source_phase),
    KEY idx_theme_leader_category (trading_date, theme_category, sub_theme)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
