CREATE TABLE IF NOT EXISTS promotion_review_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trading_date DATE NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    stock_name VARCHAR(120),
    theme_tag VARCHAR(120),
    source VARCHAR(40) NOT NULL,
    research_role VARCHAR(60),
    current_status VARCHAR(60) NOT NULL,
    previous_status VARCHAR(60),
    review_reason VARCHAR(1000),
    evidence_score DECIMAL(12,4),
    risk_blocker BOOLEAN NOT NULL DEFAULT FALSE,
    governance_blocker BOOLEAN NOT NULL DEFAULT FALSE,
    lifecycle_stage VARCHAR(40),
    theme_importance_score DECIMAL(12,4),
    tradable_score DECIMAL(12,4),
    radar_score DECIMAL(12,4),
    replay_metric_score DECIMAL(12,4),
    explain_miss_reason VARCHAR(1000),
    reviewer VARCHAR(120),
    reviewed_at TIMESTAMP NULL,
    decision_reason VARCHAR(1000),
    payload_json JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_promotion_review_item_source (trading_date, symbol, theme_tag, source),
    INDEX idx_promotion_review_item_date_status (trading_date, current_status),
    INDEX idx_promotion_review_item_symbol_date (symbol, trading_date),
    INDEX idx_promotion_review_item_theme_date (theme_tag, trading_date),
    INDEX idx_promotion_review_item_source_date (source, trading_date)
);

CREATE TABLE IF NOT EXISTS promotion_review_audit (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    review_item_id BIGINT,
    trading_date DATE NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    from_status VARCHAR(60),
    to_status VARCHAR(60),
    action VARCHAR(40) NOT NULL,
    actor VARCHAR(120),
    reason VARCHAR(1000),
    payload_json JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_promotion_review_audit_item (review_item_id),
    INDEX idx_promotion_review_audit_date_symbol (trading_date, symbol),
    CONSTRAINT fk_promotion_review_audit_item FOREIGN KEY (review_item_id) REFERENCES promotion_review_item(id)
);
